### ISSUE TITLE
Sega-accurate compression should be padded to even length

### ISSUE THREAD

**Issue by OrionNavattan** [Clownacy/clownnemesis#1]
Installing this compressor in my Sonic 2 disasm resulted in about a third of the Nemesis files not compressing identical to the original. I investigated a handful of the affected files, and the sole difference was that they were missing a single zero byte at the end. I would guess that Sega's original compressor inserted this extra byte if necessary to bring it to an even length.

**Comment by Clownacy** [comment]
It's possible that Sonic Team just used an 'even' macro after including each Nemesis file, and the disassembly accidentally included the padding in its files when the data was first split.

**Comment by OrionNavattan** [comment]
That does seem to be the case for most of them. The file for the MCZ drawbridge logs takes it even further: the padding that should be generated by the `cnop -Size_of_SEGA_sound, $8000` has instead been attached to the end of the file all these years! Amazing that went unnoticed for so long.

Anyhow, issue resolved.
