### ISSUE TITLE
Error with "decompression" by compressing specific file

### ISSUE THREAD

**Issue by MDTravisYT** [Clownacy/clownnemesis#2]
Trying to compress a small file, it errors with "Could not decompress data", despite trying to **compress** the data. It works fine with other files I try, just this specific file doesn't work. It works fine with FW-KENSC, so I'm not sure why it doesn't work here.
[index.zip](https://github.com/Clownacy/clownnemesis/files/14625720/index.zip)
![image](https://github.com/Clownacy/clownnemesis/assets/59547361/32ac2de0-7e66-4377-b0e4-7ea08a67e51b)

**Comment by Clownacy** [comment]
Nemesis can only compress data whose size is a multiple of 0x20 bytes. Flamewing's compressor must be inserting padding in order to work.

**Comment by MDTravisYT** [comment]
Can that not be done here?

**Comment by Clownacy** [comment]
I would rather not: if padding is inserted, then decompressing the compressed data will produce data with padding at the end. Compression should not harm the integrity of the encoded data.

**Comment by MDTravisYT** [comment]
I think it should be an option, or at least give you a reason on why the data couldn't compress. I wouldn't have known about this size multiple otherwise.

**Comment by MDTravisYT** [comment]
In my use case, it'd be useful for it to be an option. Due to the way SonLVL functions with Nemesis files, I've been saving them as uncompressed, and afterwards manually use FW-KENSC to compress the files to include into a Ristar hack I'm doing. This has become tedious, and I've wanted to automate it in the build script. **clownnemesis** would be perfect for this, but it creates an even more tedious situation where I have to manually pad out the uncompressed files in order for it to work properly.

**Comment by Clownacy** [comment]
I prefer having sane defaults to having options. Having options for every little thing leads to issues like RetroArch's insanely-bloated options menu, and it creates extra code to maintain and test.

Nemesis is meant for compressing tiles. Tiles are 0x20 bytes each, which is why the limit exists.

**Comment by chobocoda** [comment]
![Dreamybull_Toungeout](https://github.com/Clownacy/clownnemesis/assets/67650357/2b4a1dbf-6bc1-4969-863d-eac0a7b0a0e3)

**Comment by MDTravisYT** [comment]
> I prefer having sane defaults to having options. Having options for every little thing leads to issues like RetroArch's insanely-bloated options menu, and it creates extra code to maintain and test.
> 
> Nemesis is meant for compressing tiles. Tiles are 0x20 bytes each, which is why the limit exists.

Sure, it may be intended for tiles, but there are games that use Nemesis for other uses. For instance, Sonic CD uses Nemesis compression for storing 16x16 level tiles.

**Comment by kirisamemofo** [comment]
> Sure, it may be intended for tiles, but there are games that use Nemesis for other uses. For instance, Sonic CD uses Nemesis compression for storing 16x16 level tiles.

I'm late with this, but I checked. Every decompressed block data length is a multiple of 0x20. This applies to all prototypes, too.
